# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterLearnMix' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #绝对路径
#  flutter_application_path = '/Users/himin/Desktop/Web/FlutterProject/flutter_learn_mix/Flutter/flutter_module/'
  #相对路径
  flutter_application_path = '../../Flutter/flutter_module/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

end
